FROM mardy/qt:xenial-qt512

RUN apt update && \
    apt install -y libavcodec-dev \
                    libavdevice-dev \
                    libavformat-dev \
                    libcurl4-openssl-dev \
                    zlib1g-dev \
                    libx264-dev \
                    libjack-dev \
                    libpulse-dev \
                    libasound-dev \
                    libmbedtls-dev \
                    libfdk-aac-dev \
                    libvlc-dev \
                    libv4l-dev \
                    libudev-dev \
                    libspeexdsp-dev \
                    libfreetype6-dev \
                    libfontconfig1-dev \
                    swig \
                    libpython3-dev \
                    libluajit-5.1-dev \
                    wget \
                    freeglut3 \
                    libegl1-mesa \
                    libcups2

